@gameId = 52

### Start a new game
POST http://localhost:8080/api/lingo
Accept: application/json

### List all games
GET http://localhost:8080/api/lingo
Accept: application/json

### Get a game by id (replace {{gameId}} with the id from the POST response)
GET http://localhost:8080/api/lingo/{{gameId}}
Accept: application/json

### Make a guess for a game (replace {{gameId}})
PATCH http://localhost:8080/api/lingo/{{gameId}}
Content-Type: application/json

{
  "attempt": "nadien"
}

### Start a new round for a game (replace {{gameId}})
PATCH http://localhost:8080/api/lingo/{{gameId}}/round
Accept: application/json
